name: 'TestBeats Publish Action'
description:
  'Publish test results to Microsoft Teams, Google Chat, Slack and other
  platforms'
author: 'TestBeats'

branding:
  icon: 'bar-chart-2'
  color: 'blue'

inputs:
  config:
    description: 'Path to Testbeats configuration file'
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'
